me: Update Referee System on Lab Computer Automatically
on:
  push:
    branches:
      main


    jobs:
      build:
        name: Deployment
          runs-on: ubuntu-latest
            steps:
                - name: executing remote ssh commands with password
                  uses: appleboy/ssh-action@master
                    with:
                      host: ${{ secrets.HOST }}
                        username: ${{ secrets.USERNAME }}
                          password: ${{secrets.PASSWORD }}
                            port: ${{ secrets.PORT }}
                              script: |
                                ./referee/setup.sh
